apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ .Values.mongoExpress.replicas }}
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: {{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}
        imagePullPolicy: {{ .Values.mongoExpress.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongoExpress.service.targetPort }}
        resources:
          {{- toYaml .Values.mongoExpress.resources | nindent 10 }}
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: mongo