apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: mongo-express
  ports:
  - port: {{ .Values.mongoExpress.service.port }}
    targetPort: {{ .Values.mongoExpress.service.targetPort }}
  type: {{ .Values.mongoExpress.service.type }}