# argocd-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: numgen-app
  namespace: argocd
  annotations:
    # Image Updater annotations
    argocd-image-updater.argoproj.io/image-list: numgen=475325513391.dkr.ecr.ap-southeast-2.amazonaws.com/nomcombo-app
    argocd-image-updater.argoproj.io/numgen.update-strategy: latest
    argocd-image-updater.argoproj.io/numgen.helm.image-name: numgen.image.repository
    argocd-image-updater.argoproj.io/numgen.helm.image-tag: numgen.image.tag
    argocd-image-updater.argoproj.io/numgen.allow-tags: regex:^[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: feature/image-updater
  labels:
    app: numgen
spec:
  project: default
  source:
    repoURL: "https://github.com/slimboi/NodeJS-NumberGeneratorApp.git"
    targetRevision: feature/image-updater
    path: numgen-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: numgen-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m