# ===== values-numgen.yaml (with MongoDB configuration added) =====
# NumGen Application Configuration
app:
  name: numgen
  namespace: numgen-app
  labels:
    app: numgen
    component: frontend

# Image configuration
image:
  repository: 475325513391.dkr.ecr.ap-southeast-2.amazonaws.com/nomcombo-app
  tag: "v3"
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  replicas: 2
  strategy:
    type: RollingUpdate

# Container configuration
container:
  name: numgen
  port: 3000

# Environment variables
env:
  - name: NODE_ENV
    value: "production"
  - name: PORT
    value: "3000"
  - name: MONGO_URI
    value: "mongodb://{{ .Release.Name }}-mongodb:27017/nomcomboDB"  # Updated to use Bitnami service name

# Service configuration
service:
  enabled: true
  type: NodePort
  port: 3000
  targetPort: 3000

# Resource limits
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Auto-scaling configuration
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Health checks
probes:
  readiness:
    enabled: true
    type: httpGet
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    enabled: true
    type: httpGet
    httpGet:
      path: /
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Security configuration
security:
  imagePullSecrets:
    - name: ecr-secret

# Persistence (disabled for NumGen)
persistence:
  enabled: false

# Additional volumes
volumes: []
volumeMounts: []

# =============================================================================
# MongoDB Configuration (Bitnami Chart)
# This configures the MongoDB dependency when deploying NumGen
# =============================================================================
mongodb:
  enabled: true
  
  # Authentication (disabled to match your current setup)
  auth:
    enabled: false
    # If you want to enable auth later:
    # rootUser: root
    # rootPassword: ""
    # username: numgen
    # password: ""
    # database: nomcomboDB

  # Architecture
  architecture: standalone  # or replicaset for production

  # Persistence (matching your old 1Gi requirement)
  persistence:
    enabled: true
    storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi

  # Resources (matching your old configuration)
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

  # Service configuration
  service:
    type: ClusterIP
    ports:
      mongodb: 27017

  # Health checks (using Bitnami defaults)
  livenessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 10
    failureThreshold: 6

  readinessProbe:
    enabled: true
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 10
    failureThreshold: 6