# ===== templates/mongodb-connection-secret.yaml =====
apiVersion: v1
kind: Secret
metadata:
  name: numgen-stack-mongodb-connection
  namespace: {{ .Values.global.namespace }}
type: Opaque
data:
  mongodb-uri: {{ printf "mongodb://%s:%s@%s-mongodb:27017/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password .Release.Name .Values.mongodb.auth.database | b64enc }}