# ===== values.yaml (Default values for linting and fallback) =====
# This file provides default values for Helm linting and serves as a fallback
# Use specific values-*.yaml files for actual deployments

# Application metadata
app:
  name: default-app
  namespace: default
  labels:
    app: default-app
    component: application

# Image configuration
image:
  repository: nginx
  tag: "latest"
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  replicas: 1
  strategy:
    type: RollingUpdate

# Container configuration
container:
  name: default-app
  port: 80

# Environment variables (empty by default)
env: []

# Service configuration
service:
  enabled: true
  type: ClusterIP
  port: 80
  targetPort: 80

# Resource limits
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Auto-scaling configuration (disabled by default)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

# Health checks (disabled by default for generic linting)
probes:
  readiness:
    enabled: false
    type: httpGet
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 10
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3
  liveness:
    enabled: false
    type: httpGet
    httpGet:
      path: /
      port: 80
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

# Security configuration
security:
  imagePullSecrets: []

# Persistence (disabled by default)
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi
  mountPath: /data

# Additional volumes (empty by default)
volumes: []
volumeMounts: []