helm:
  parameters:
  - name: image.name
    value: slimboi/numcombo-app
    forcestring: true
  - name: image.tag
    value: b7f8c0a
    forcestring: true
  - name: numgen.image.repository
    value: slimboi/numcombo-app
    forcestring: true
  - name: numgen.image.tag
    value: 9d33302
    forcestring: true
