# values-dev.yaml - Development Environment Overrides
global:
  namespace: numgen-dev
  environment: development

numgen:
  app:
    namespace: numgen-dev
  
  deployment:
    replicas: 1  # Reduced from 4 for dev
  
  env:
    - name: NODE_ENV
      value: "development"  # Changed from production
    - name: PORT
      value: "3000"
    - name: DEBUG
      value: "true"  # Additional dev variable
    - name: MONGO_URI
      valueFrom:
        secretKeyRef:
          name: "{{ .Release.Name }}-mongodb-connection"
          key: mongodb-uri
  
  resources:
    requests:
      memory: "64Mi"   # Reduced from 128Mi
      cpu: "50m"       # Reduced from 100m
    limits:
      memory: "128Mi"  # Reduced from 256Mi
      cpu: "100m"      # Reduced from 200m

mongoExpress:
  app:
    namespace: numgen-dev
  enabled: true  # Keep enabled for dev debugging

mongodb:
  auth:
    rootPassword: "DevRootPassword123!"
    password: "DevUserPassword123!"
    database: "nomcomboDB-dev"
  
  persistence:
    size: 500Mi  # Smaller than default 1Gi
  
  resources:
    requests:
      memory: "128Mi"  # Reduced from 256Mi
      cpu: "100m"      # Reduced from 250m
    limits:
      memory: "256Mi"  # Reduced from 512Mi
      cpu: "200m"      # Reduced from 500m
